# Generated by Django 5.2.7 on 2025-10-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], db_index=True, default='lost', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('creationDate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creationDate'],
            },
        ),
    ]
