# Generated by Django 5.2.7 on 2025-10-06 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_verificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], db_index=True, default='lost', max_length=10)),
                ('location', models.TextField(blank=True, max_length=200)),
                ('creationDate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creationDate'],
            },
        ),
    ]
