# Generated by Django 5.2.7 on 2025-10-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_itempost_contact_email_itempost_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='item_images/'),
        ),
    ]
