services:
  db:
    image: postgres:16
    container_name: lf_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lf_db
      POSTGRES_USER: lf_user
      POSTGRES_PASSWORD: lf_password_123
    ports:
      - "5432:5432"
    volumes:
      - lf_pgdata:/var/lib/postgresql/data

volumes:
  lf_pgdata:
