# Generated by Django 5.2.7 on 2025-11-20 03:07

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingsignup',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Digits only, optionally starting with + (7-15 digits).', max_length=20, null=True, validators=[users.validators.validate_phone_number]),
        ),
    ]
